modLoader="javafml"
loaderVersion="[24,]"
issueTrackerURL="https://github.com/Ecdcaeb/Custom-Colorful-Enchantment/issues"
logoFile=""
license="GUNv3"

[[mods]]
modId="custom_colorful_enchantment"
# We use the global forge version
version="1.0.3"
updateJSONURL=""
displayName="Custom Colorful Enchantment"
credits=""
authors="Hileb"
description='''a mod that enable modder and player adjust the color of enchantment.
    '''
[[dependencies.custom_colorful_enchantment]]
modId="forge"
mandatory=true
versionRange="[46,)"
ordering="AFTER"
side="CLIENT"
[[dependencies.custom_colorful_enchantment]]
modId="minecraft"
mandatory=true
versionRange="[1.20,)"
ordering="AFTER"
side="CLIENT"